DELETE FROM T_KPI_SALES;
DELETE FROM T_TRANSACTION;
DELETE FROM T_PAYMENT_METHOD;
DELETE FROM T_ORDER_ITEM_DISCOUNT;
DELETE FROM T_ORDER_ITEM;
DELETE FROM T_ORDER_DISCOUNT;
DELETE FROM T_ORDER;
DELETE FROM T_BUSINESS;
