spring:
  flyway:
    clean-disabled: true

  jpa:
    show-sql: false

  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}

wutsi:
  client-id: checkout-access
  #  application:
  #    jobs:
  #      compute-yesterday-sales-kpi:
  #        cron: "0 10 0 * * *"  # Runs every day at 00:10 AM
  #      compute-today-sales-kpi:
  #        cron: "0 15 * * * *"  # Runs every hour at *:15
  platform:
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
        ttl: 86400
    payment:
      flutterwave:
        test-mode: false
        secret-key: ${FLUTTERWAVE_SECRET_KEY}
        secret-hash: ${FLUTTERWAVE_SECRET_HASH}
        encryption-key: ${FLUTTERWAVE_ENCRYPTION_KEY}
    security:
      type: none
    storage:
      type: aws
      aws:
        bucket: prod-wutsi-data

