server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,flyway,health,info,scheduledtasks"

spring:
  main:
    lazy-initialization: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null

  flyway:
    baseline-on-migrate: true
    clean-disabled: false

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming:
        physical-strategy: com.wutsi.platform.core.util.CustomPhysicalNamingStrategy

  datasource:
    url: "jdbc:mysql://localhost:3306/checkout?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password:
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      idle-timeout: 10000 #maximum idle time for connection
      minimum-idle: 8 #minimum number of idle connections maintained by HikariCP in a connection pool
      minimum-pool-size: 8 #maximum pool size
      maximum-pool-size: 8 #maximum pool size
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.

wutsi:
  client-id: checkout-access
  application:
    name: checkout-access
    jobs:
      compute-yesterday-sales-kpi:
        cron: "0 10 * * * *"  # Runs every hour at *:10
      compute-today-sales-kpi:
        cron: "0 15 * * * *"  # Runs every hour at *:15
    cashout:
      delay-days: 1 # Wait for cashout
    services:
      fees-calculator:
        transaction-fees:
          - country: CM  # 10% on charges with Mobile account
            transaction-type: CHARGE
            payment-method-type: MOBILE_MONEY
            percent: 10
            amount: 0
          - country: CM  # 20% on donations with Mobile account
            transaction-type: DONATION
            payment-method-type: MOBILE_MONEY
            percent: 20
            amount: 0
          - country: CM  # Free cash-out to Mobile account
            transaction-type: CASHOUT
            payment-method-type: MOBILE_MONEY
            percent: 0
            amount: 0
          - country: CM  # 3500F cash-out to Bank account
            transaction-type: CASHOUT
            payment-method-type: BANK
            percent: 0
            amount: 3500

  platform:
    cache:
      name: ${wutsi.application.name}
      type: local
    payment:
      flutterwave:
        enabled: true
        test-mode: true
        secret-key: "-----"
        secret-hash: "----"
        encryption-key: "----"
    security:
      type: none
    storage:
      type: local
      local:
        directory: "${user.home}/wutsi/storage"
    tracing:
      client-id: ${wutsi.application.name}
      device-id-provider:
        type: header

logging:
  level:
    root: INFO
    com.wutsi.checkout.access: DEBUG
  pattern:
    console: "%d type=%level logger=%class{20} thread=%thread %m%n"
    file: "%d type=%level logger=%class{20} thread=%thread %m%n"


