ALTER TABLE T_TRANSACTION ADD COLUMN payment_method_number VARCHAR(30) NOT NULL;
ALTER TABLE T_TRANSACTION  ADD COLUMN payment_method_country VARCHAR(2);
ALTER TABLE T_TRANSACTION  ADD COLUMN payment_method_owner_name VARCHAR(100) NOT NULL;
ALTER TABLE T_TRANSACTION  ADD COLUMN payment_method_type INT NOT NULL;
ALTER TABLE T_TRANSACTION ADD COLUMN payment_provider_fk BIGINT NOT NULL REFERENCES T_PAYMENT_PROVIDER(id);
ALTER TABLE T_TRANSACTION  ADD COLUMN email VARCHAR(255);

ALTER TABLE T_TRANSACTION MODIFY payment_method_fk BIGINT;
