ALTER TABLE T_BUSINESS ADD COLUMN total_orders BIGINT NOT NULL DEFAULT 0;
ALTER TABLE T_BUSINESS ADD COLUMN total_units BIGINT NOT NULL DEFAULT 0;
ALTER TABLE T_BUSINESS ADD COLUMN total_value BIGINT NOT NULL DEFAULT 0;
