ALTER TABLE T_ORDER_DISCOUNT ADD COLUMN discount_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE T_ORDER_DISCOUNT RENAME COLUMN code to name;

ALTER TABLE T_ORDER_ITEM_DISCOUNT ADD COLUMN discount_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE T_ORDER_ITEM_DISCOUNT RENAME COLUMN code to name;
